-- Exploratory Data Analysis EDA
-- aim to understand data using basic queries, data profiling simple agregation and subquarries

--------------------
-- Exploration
--------------------
-- Explore all objects in the Database 
SELECT * FROM INFORMATION_SCHEMA.TABLES
-- Explore all columns in a specific table
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'erp_px_cat_giv2'

-- Dimension exploration 
-- explore all countres customers come from
SELECT DISTINCT country
FROM gold.dim_customers
-- explore all categories
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY category, subcategory, product_name

-- Date exploration 
-- find date of first and last order, how many years of sales are avaliable
SELECT MIN(order_date) AS first_order_date, MAX(order_date) AS last_order_date,
       DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS years_of_sales
FROM gold.fact_sales
-- find youngest and oldest customers
SELECT MIN(birthdate) AS oldest_customer,
DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
 MAX(birthdate) AS youngest_customer,
DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers

-- Measure exploration 
-- find total sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales
-- find how many items sold
SELECT SUM(quantity) AS total_items_sold
FROM gold.fact_sales
-- find average sales 
SELECT AVG(price) AS average_price
FROM gold.fact_sales
-- total number of orders
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales
-- total number of products
SELECT COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
-- total number of customers
SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers

---------------------
-- Measure Reporting
---------------------
SELECT 'Total Sales' as measure_name, SUM(sales_amount) AS meausure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Items Sold', SUM(quantity) FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number)FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(DISTINCT product_key) FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(DISTINCT customer_key) FROM gold.dim_customers


-- magnitude analysis , understand importance of different cata by compare vlaues by cata
-- find total costomers by countries
SELECT country, COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC
-- find total customers by gender
SELECT gender, COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC
-- total products by cata
SELECT category, COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC
--avergae cost in each cata
SELECT category, AVG(cost) AS average_price
FROM gold.dim_products
GROUP BY category
ORDER BY average_price DESC
-- total revenue generated by each cata
SELECT p.category, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC
-- total recenye generated by each customer
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC
-- distribution of sold items acrose countries
SELECT c.country, SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY  c.country
ORDER BY total_items_sold DESC

-- ranking analysis,order values of dim by measure 
-- 5 products generate highest revenue
SELECT TOP 5 p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
     -- use window functions
    SELECT * FROM(
    SELECT p.product_name, 
    SUM(f.sales_amount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(f.sales_amount) DESC) AS revenue_rank
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p ON f.product_key = p.product_key
    GROUP BY p.product_name)t
    WHERE revenue_rank <= 5
-- 5 worst performing product by revenue
SELECT TOP 5 p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC
    -- use window functions
    SELECT * FROM(
    SELECT p.product_name, 
    SUM(f.sales_amount) AS total_revenue,
    RANK() OVER (ORDER BY SUM(f.sales_amount) ASC) AS revenue_rank
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p ON f.product_key = p.product_key
    GROUP BY p.product_name)t
    WHERE revenue_rank <= 5 
-- top 10 customers who generated highest revenue 
SELECT TOP 10 c.customer_key,c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC
-- 3 customers with fewest orders placed 
SELECT TOP 3 c.customer_key,c.first_name, c.last_name, COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_orders ASC  